ROLE_TRAFFIC_OFFICER = "traffic_officer"
ROLE_SUBCITY_OFFICER = "subcity_officer"
ROLE_COMPLAINT_OFFICER = "complaint_officer"
ROLE_SYSTEM_ADMIN = "system_admin"

VIOLATION_STATUS_REPORTED = "REPORTED"
VIOLATION_STATUS_BROADCASTED = "BROADCASTED"
VIOLATION_STATUS_UNDER_COMPLAINT = "UNDER_COMPLAINT"
VIOLATION_STATUS_CONFIRMED = "CONFIRMED"
VIOLATION_STATUS_PAYMENT_PENDING = "PAYMENT_PENDING"
VIOLATION_STATUS_PAID = "PAID"
VIOLATION_STATUS_REVOKED = "REVOKED"

ALERT_STATUS_PENDING = "PENDING"
ALERT_STATUS_ACKNOWLEDGED = "ACKNOWLEDGED"

COMPLAINT_STATUS_OPEN = "OPEN"
COMPLAINT_STATUS_CONFIRMED = "CONFIRMED"
COMPLAINT_STATUS_REVOKED = "REVOKED"

PAYMENT_STATUS_REQUESTED = "REQUESTED"
PAYMENT_STATUS_PAID = "PAID"
PAYMENT_STATUS_FAILED = "FAILED"

OUTBOX_STATUS_PENDING = "PENDING"
OUTBOX_STATUS_DELIVERED = "DELIVERED"
OUTBOX_STATUS_FAILED = "FAILED"

