#!/usr/bin/env bash
set -euo pipefail

db_admin_user="${POSTGRES_USER:-supabase_admin}"

psql -v ON_ERROR_STOP=1 --username "${db_admin_user}" --dbname "${POSTGRES_DB}" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_APP_USER}') THEN
      CREATE ROLE ${DB_APP_USER} LOGIN PASSWORD '${DB_APP_USER_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_WORKER_USER}') THEN
      CREATE ROLE ${DB_WORKER_USER} LOGIN PASSWORD '${DB_WORKER_USER_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_AUTHENTICATOR_USER}') THEN
      CREATE ROLE ${DB_AUTHENTICATOR_USER} LOGIN PASSWORD '${DB_AUTHENTICATOR_USER_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${DB_STORAGE_USER}') THEN
      CREATE ROLE ${DB_STORAGE_USER} LOGIN PASSWORD '${DB_STORAGE_USER_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      CREATE ROLE anon NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
      CREATE ROLE authenticated NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
      CREATE ROLE service_role NOLOGIN BYPASSRLS;
    END IF;
  END
  \$\$;

  ALTER ROLE ${DB_APP_USER} WITH LOGIN PASSWORD '${DB_APP_USER_PASSWORD}';
  ALTER ROLE ${DB_WORKER_USER} WITH LOGIN PASSWORD '${DB_WORKER_USER_PASSWORD}';
  ALTER ROLE ${DB_AUTHENTICATOR_USER} WITH LOGIN PASSWORD '${DB_AUTHENTICATOR_USER_PASSWORD}' NOINHERIT;
  ALTER ROLE ${DB_STORAGE_USER} WITH LOGIN PASSWORD '${DB_STORAGE_USER_PASSWORD}' NOINHERIT CREATEROLE NOREPLICATION;
  ALTER ROLE anon WITH NOLOGIN NOINHERIT;
  ALTER ROLE authenticated WITH NOLOGIN NOINHERIT;
  ALTER ROLE service_role WITH NOLOGIN NOINHERIT BYPASSRLS;

  GRANT CONNECT, TEMPORARY ON DATABASE ${POSTGRES_DB} TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_AUTHENTICATOR_USER}, ${DB_STORAGE_USER};
  GRANT USAGE, CREATE ON SCHEMA public TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_STORAGE_USER};
  GRANT USAGE ON SCHEMA public TO ${DB_AUTHENTICATOR_USER};
  GRANT anon TO ${DB_AUTHENTICATOR_USER};
  GRANT authenticated TO ${DB_AUTHENTICATOR_USER};
  GRANT service_role TO ${DB_AUTHENTICATOR_USER};
  GRANT anon TO ${DB_STORAGE_USER};
  GRANT authenticated TO ${DB_STORAGE_USER};
  GRANT service_role TO ${DB_STORAGE_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_STORAGE_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_STORAGE_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_STORAGE_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${DB_APP_USER}, ${DB_WORKER_USER}, ${DB_STORAGE_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_APP_USER} IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO ${DB_WORKER_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_APP_USER} IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO ${DB_WORKER_USER};

  CREATE SCHEMA IF NOT EXISTS storage AUTHORIZATION ${DB_STORAGE_USER};
  ALTER SCHEMA storage OWNER TO ${DB_STORAGE_USER};
  GRANT USAGE ON SCHEMA storage TO ${DB_AUTHENTICATOR_USER}, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON SCHEMA storage TO ${DB_STORAGE_USER};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_STORAGE_USER} IN SCHEMA storage GRANT ALL PRIVILEGES ON TABLES TO anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_STORAGE_USER} IN SCHEMA storage GRANT ALL PRIVILEGES ON FUNCTIONS TO anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_STORAGE_USER} IN SCHEMA storage GRANT ALL PRIVILEGES ON SEQUENCES TO anon, authenticated, service_role;
EOSQL
